"""add event_date to bookings

Revision ID: 801add35c25b
Revises: 0b2bed1411a3
Create Date: 2026-04-03 09:22:44.499217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801add35c25b'
down_revision = '0b2bed1411a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('event_date')

    # ### end Alembic commands ###
